In [67]:
mesic=[]
rok=int(input("Zadej rok: "))
x=int(input("Zadej měsíc: "))-1
posledni=input("Zadej poslední odpolední službu: ").upper()
poho=input("Zadej poslední pohotovost: ").upper()

Zadej rok: 2023
Zadej měsíc: 4
Zadej poslední odpolední službu: lll
Zadej poslední pohotovost: sss

In [68]:
import numpy as np
import pandas as pd
import calendar
from tabulate import tabulate

svatky=[[1,1],[5,1],[5,8],[7,5],[7,6],[9,28],[10,28],[11,17],[12,24],[12,25],[12,26],[4,7],[4,10]]

dny_v_tydnu= ("Po ","Út ","St ","Čt ","Pá ","So ","Ne ")
barveni = {"LLL":"#ddd9c4","SSS":"#92cddc","PPP":"#c4d79b","III":"#e26b0a"}

osoby = [["SSS","#92cddc",0],
         ["LLL","#ddd9c4",1],
         ["PPP","#c4d79b",2],
         ["III","#e26b0a",3]]     

nazvy_mesicu =("Leden","Únor","Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec")
nadpis = ("DEN","RANO","ODPO","POH")
obj = calendar.Calendar()

class Clovek():
  def __init__(self,p):
    self.index=p
    self.znacka=osoby[p][0]
    self.barva=osoby[p][1]
    # Podmínka: LICHÝ vs SUDÝ počet osob
    if len(osoby)%2==0:
      if p%2==0: 
        # Sudý řádky posunu o +1 hodnotu vpřed
        self.predchudce=osoby[p-len(osoby)+1][0]
        # Podmínka: NASLEDUJICI: poslední sudý řádek se odkáže na začátek osoby[index=0]
        if len(osoby)-2==p:  
          self.nasledujici=osoby[len(osoby)-p-2][0]
        else: 
          # Není poslední sudý řádek .. skáču o +3 indexy
          self.nasledujici=osoby[p+3-len(osoby)][0]      
      else: 
        # Lichý řádky: Posunu se o -1 hodnotu zpět
        self.predchudce=osoby[p-len(osoby)-1][0]
        # Podmínka: NASLEDUJICI: poslední lichý řádek se odkáže na první lichý záznam (tj. začátek osoby[index=1])
        if len(osoby)-1==p: 
          self.nasledujici=osoby[len(osoby)-p][0]
        else:
          self.nasledujici=osoby[p+1-len(osoby)][0]
    else: 
      # Lichý počet osob: řazení je automatické, netřeba ošetřovat
      self.predchudce=osoby[p-1][0]
      self.nasledujici=osoby[p-len(osoby)+1][0]
########
#Rozpis#
########
class Rozpis:
  def __init__(self,p):
    self.index=p
    self.rok=rok
    self.mesic=p+1
    self.nazev=nazvy_mesicu[p]
    kal = calendar.monthrange(self.rok,self.mesic)
    self.prvni_den = kal[0]
    self.jmeno_dne = dny_v_tydnu[self.prvni_den]
    self.delka_dnu = kal[1]
    
    pocet=[]
    for _ in range(self.delka_dnu):
      pocet.append(_+1)
    self.pocet=pocet

    self.matice= np.zeros((self.delka_dnu,4),dtype=object)
    
    for k in range(len(svatky)):
      if svatky[k][0] == self.mesic:
        for jk in range(self.delka_dnu):
          if svatky[k][1] == self.pocet[jk]:
            self.matice[jk,1]="X"
            self.matice[jk,2]="X"


    #rozpis_dnu(self.prvni_den,self.delka_dnu,posledni)



def rozpis_dnu(den,poc,posledni,poho):
  poradi=1 # rozhoduje o použití PREDCHUDCE (poradi=-1) x NASLEDOVNIK (poradi=1)
  for k in range(len(osoby)):
    if poho == osoby[k][0]:
      index=k

  for i in range(poc):
    for j in range(2):
      mesic[x].matice[i,0]=dny_v_tydnu[den]
      if (5 <= den <= 6):
        mesic[x].matice[i,j+1]=""
      else:
        posledni=predej(posledni,poradi)
        if mesic[x].matice[i,j+1]=="X":
          mesic[x].matice[i,j+1]=""
        else:
          mesic[x].matice[i,j+1]=posledni
          # poradi se meni pouze u sudych osob
        if len(osoby)%2==0:
          poradi*=-1
    mesic[x].matice[i,3]=osoby[index][0]
    if den == 6:
      den=0
      if index == len(osoby)-1:
        index=0
      else:
        index+=1

    else:
      
      den+=1
  #return matice

def predej(posledni,poradi):
  for kl in range(len(osoby)):
    if posledni==clovek[kl].znacka:
      if poradi==-1:
        posledni=clovek[kl].predchudce
      else:
        posledni=clovek[kl].nasledujici
      break  
  return posledni

clovek=[]
obj = calendar.Calendar()
#posledni="LAN"
mesic=[]
for p in range(12):
  mesic.append(Rozpis(p))
 
  

for p in range(len(osoby)):
  clvk=Clovek(p)
  clovek.append(clvk)

for i in range(len(osoby)):
 print(vars(clovek[i]))


poc=mesic[x].delka_dnu
den=mesic[x].prvni_den
pocet=[]

#matice = np.zeros((poc,4),dtype=object)
rozpis_dnu(den, poc, posledni,poho)

{'index': 0, 'znacka': 'SSS', 'barva': '#92cddc', 'predchudce': 'LLL', 'nasledujici': 'III'}
{'index': 1, 'znacka': 'LLL', 'barva': '#ddd9c4', 'predchudce': 'SSS', 'nasledujici': 'PPP'}
{'index': 2, 'znacka': 'PPP', 'barva': '#c4d79b', 'predchudce': 'III', 'nasledujici': 'SSS'}
{'index': 3, 'znacka': 'III', 'barva': '#e26b0a', 'predchudce': 'PPP', 'nasledujici': 'LLL'}

In [69]:
def obarvi(col, pattern_map, default=''):
  return np.select(
      [col.str.contains(k, na=False) for k in pattern_map.keys()],
      [f'background-color: {v}' for v in pattern_map.values()],
      default=default
    ).astype(str)

zadani=mesic[x].matice

data = pd.DataFrame(zadani, index=mesic[x].pocet, columns=nadpis)
data.style.apply(obarvi,
               pattern_map=barveni, 
                 subset=["RANO","ODPO","POH"])

In [ ]:
 print(vars(mesic[x]))

In [ ]:
for i in range(len(nazvy_mesicu)):
 print(vars(mesic[i]))